name: Deploy Wikismiley on Azure App Services ğŸ“¨

on:
  push:
    branches: [ "main" ]

env:
  AZURE_WEBAPP_NAME: wa-wiki-smiley

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checks out repo's code ğŸ“¥
      uses: actions/checkout@v3

    - name: Sets up Node.js ğŸ—ï¸
      uses: actions/setup-node@v3
      with:
        node-version: 18 
        cache: 'npm'

    - name: Installs dependencies â¬‡ï¸
      run: |
        npm prune --production
        npm ci

    - name: Builds the Svelte app âš’ï¸
      run: npm run build --if-present

    - name: Zips the build artifacts ğŸ“¦
      run: zip -r build.zip .

    - name: Saves build artifacts ğŸ’¾
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Downloads build artifacts ğŸ“¥
      uses: actions/download-artifact@v3
      with:
        name: build
    
    - name: Unzips the build artifacts ğŸ“¦
      run: |
        unzip build.zip 
        rm build.zip

    - name: Deploys to Azure Web App ğŸŒ
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '.'
