name: Deploy Wikismiley on Azure App Services ğŸ“¨

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checks out repo's code ğŸ“¥
      uses: actions/checkout@v3

    - name: Sets up Node.js ğŸ—ï¸
      uses: actions/setup-node@v3
      with:
        node-version: 18 

    - name: Installs dependencies â¬‡ï¸
      run: npm ci

    - name: Builds the Svelte app âš’ï¸
      run: npm run build --if-present

    - name: Save build artifacts ğŸ’¾
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checks out repo's code ğŸ“¥
      uses: actions/checkout@v3